import { ApiProperty, ApiPropertyOptional, OmitType, PartialType } from '@nestjs/swagger';
import { Transform } from 'class-transformer';
import {
  IsEmail,
  IsEnum,
  IsOptional,
  IsString,
  Length,
  Matches,
  MaxLength,
} from 'class-validator';
import { UserRole, UserStatus } from '../../schemas/auth.schema';

const textNamePattern = /^[A-Za-z][A-Za-z' -]*$/;
const usernamePattern = /^[A-Za-z0-9_.-]+$/;

export class CreateAdminUserDto {
  @ApiProperty({
    example: 'jane.user',
    minLength: 3,
    maxLength: 40,
    description: 'Unique username. Letters, numbers, dots, underscores, and hyphens only.',
  })
  @Transform(({ value }) => (typeof value === 'string' ? value.trim().toLowerCase() : value))
  @IsString()
  @Length(3, 40)
  @Matches(usernamePattern, {
    message: 'username can only contain letters, numbers, dots, underscores, and hyphens',
  })
  username: string;

  @ApiProperty({
    example: 'strongpass123',
    minLength: 8,
    maxLength: 128,
    description: 'Initial password. Stored only as a salted hash.',
  })
  @IsString()
  @Length(8, 128)
  password: string;

  @ApiProperty({
    example: 'jane@example.com',
    maxLength: 254,
    description: 'User email address. Request field name is emailid.',
  })
  @Transform(({ value }) => (typeof value === 'string' ? value.trim().toLowerCase() : value))
  @IsEmail()
  @MaxLength(254)
  emailid: string;

  @ApiProperty({
    example: 'Jane',
    minLength: 1,
    maxLength: 80,
    description: 'First name. Letters, spaces, apostrophes, and hyphens only.',
  })
  @Transform(({ value }) => (typeof value === 'string' ? value.trim() : value))
  @IsString()
  @Length(1, 80)
  @Matches(textNamePattern, {
    message: 'firstName can only contain letters, spaces, apostrophes, and hyphens',
  })
  firstName: string;

  @ApiPropertyOptional({
    example: 'User',
    minLength: 1,
    maxLength: 80,
    description: 'Optional last name. Letters, spaces, apostrophes, and hyphens only.',
  })
  @Transform(({ value }) => (typeof value === 'string' ? value.trim() : value))
  @IsOptional()
  @IsString()
  @Length(1, 80)
  @Matches(textNamePattern, {
    message: 'lastName can only contain letters, spaces, apostrophes, and hyphens',
  })
  lastName?: string;

  @ApiProperty({
    enum: UserRole,
    example: UserRole.User,
    description: 'Admin can assign either admin or user. Root admin is seeded only by script.',
  })
  @IsEnum(UserRole)
  role: UserRole;
}

export class UpdateAdminUserDto extends PartialType(
  OmitType(CreateAdminUserDto, ['password'] as const),
) {
  @ApiPropertyOptional({
    enum: UserRole,
    example: UserRole.User,
    description: 'Change user role. Cannot create or update root admin through this DTO.',
  })
  @IsOptional()
  @IsEnum(UserRole)
  role?: UserRole;
}

export class AdminUserResponseDto {
  @ApiProperty({ example: '665d2fb4d5f6a0a42f1f9a21' })
  id: string;

  @ApiProperty({ example: 'jane.user' })
  username: string;

  @ApiProperty({ example: 'jane@example.com' })
  emailId: string;

  @ApiProperty({ example: 'Jane' })
  firstName: string;

  @ApiPropertyOptional({ example: 'User' })
  lastName?: string;

  @ApiProperty({ enum: UserRole, example: UserRole.User })
  role: UserRole;

  @ApiProperty({ example: false })
  isRootAdmin: boolean;

  @ApiProperty({ enum: UserStatus, example: UserStatus.Active })
  status: UserStatus;

  @ApiPropertyOptional({ example: '665d2fb4d5f6a0a42f1f9a20' })
  createdByUserId?: string;

  @ApiProperty({
    example: '2026-05-20T10:30:00.000Z',
    description: 'UTC ISO 8601 timestamp generated by Mongo/Mongoose.',
  })
  createdAt: string;

  @ApiProperty({
    example: '2026-05-20T10:30:00.000Z',
    description: 'UTC ISO 8601 timestamp generated by Mongo/Mongoose.',
  })
  updatedAt: string;
}
